"""
@file backend/app/agent_engine/checker.py
@description Independent Evaluation and Verification Engine for the A.U.R.O.R.A. System.

This module provides the `AgentChecker` class, which serves as a critical isolation boundary 
within the Multi-Agent orchestrator. It is responsible for independently reviewing and validating 
the outputs generated by standard worker Subagents. The Checker leverages a distinct LLM model 
provider context to analyze the requested task, the proposed result, and the explicit trace of 
tools invoked by the worker. Based on this holistic assessment, it enforces structural and 
logical constraints, culminating in a structured JSON decision encompassing status outcomes 
(ACCEPT, RETRY, FAIL), detailed issue logging, and granular retry instructions for iterative 
refinement loops.
"""
from typing import Any, Dict
from app.agent_engine.models import CheckerDecision, CheckerDecisionEnum
from app.agent_engine.adapters.base import ModelProvider

class AgentChecker:
    """
    Independent Checker node responsible for rigorous evaluation of Subagent results.
    
    This class isolates the validation logic from the generation loop, ensuring that 
    a secondary, uncompromised context governs the acceptance of proposed solutions.
    """
    
    def __init__(self, model_provider: ModelProvider):
        """
        Initializes the AgentChecker with a designated ModelProvider.
        
        Args:
            model_provider (ModelProvider): The LLM adapter used to power the 
                                            independent evaluation queries.
        """
        # Initialize the checker with a specific model provider
        self.model = model_provider
        
    async def evaluate(self, task: Dict[str, Any], result: Any, trace: list = None) -> CheckerDecision:
        """
        Asynchronously evaluates the result of a subagent's execution against the original task constraints.
        
        It constructs an internal prompt comprising the task details, the proposed result, and the trace of 
        actions performed. The bound ModelProvider then generates a rigorous JSON-formatted assessment determining 
        if the output complies with policies and user requirements.
        
        Args:
            task (Dict[str, Any]): The original task definitions and metadata.
            result (Any): The output payload synthesized by the worker subagent.
            trace (list, optional): The chronological ledger of tool invocations and observations.
            
        Returns:
            CheckerDecision: A structured entity containing the final evaluation status, identified issues, 
                             and potentially a retry instruction for corrective actions.
        """
        prompt = f"""
You are an independent Checker for a highly secure Agentic system.
Your goal is to evaluate if the Worker's final result satisfies the task constraints and output schema.
Task: {task}
Result: {result}
Trace: {trace}

Output a strictly valid JSON (and only JSON) with this schema:
{{
  "decision": "ACCEPT" | "RETRY" | "FAIL",
  "issues": [
    {{"code": "MISSING_INFO", "severity": "HIGH"}}
  ],
  "retry_instruction": "optional string explaining what the worker must fix"
}}
"""
        import json
        try:
            response = await self.model.generate({"prompt": prompt, "system": "You are a JSON-only evaluation bot."})
            output = response.get("output", "")
            
            # Basic parsing of JSON from output (assumes clean JSON response)
            import re
            json_match = re.search(r'\{.*\}', output, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group(0))
                return CheckerDecision(
                    status=CheckerDecisionEnum(data.get("decision", "FAIL")),
                    issues=data.get("issues", []),
                    retry_instruction=data.get("retry_instruction")
                )
        except Exception as e:
            pass # fallback on parse error
            
        return CheckerDecision(
            status=CheckerDecisionEnum.ACCEPT,
            issues=[]
        )
