"""
@file backend/app/domain/models/runtime_state.py
@description SQLAlchemy persistence models for native Agent Runtime state.

This module provides the durable database records used by the Agent Runtime,
idempotency subsystem, and budget subsystem. Runtime-specific state that does
not have a dedicated relational column is stored as a serialized AgentRun
snapshot in the AgentRun.input_data field.
"""

import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, Float, String, Text

from app.domain.models.identity import Base


class AgentRun(Base):
    """
    Durable persistence record for a native Agent Runtime execution.

    The input_data column stores the complete serialized AgentRun snapshot.
    This avoids duplicating every orchestration-state field at the SQL level
    while preserving crash recovery and checkpoint reconstruction.
    """

    __tablename__ = "agent_runs"

    id = Column(
        String,
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )

    session_id = Column(
        String,
        nullable=False,
        index=True,
    )

    principal_id = Column(
        String,
        nullable=False,
        default="system",
    )

    role = Column(
        String,
        nullable=False,
        default="agent",
    )

    input_data = Column(
        Text,
        nullable=False,
    )

    status = Column(
        String,
        nullable=False,
        default="queued",
        index=True,
    )

    result = Column(
        Text,
        nullable=True,
    )

    error = Column(
        Text,
        nullable=True,
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )


class IdempotencyKey(Base):
    """
    Durable storage for idempotent tool execution results.

    The key is the canonical SHA-256 idempotency identifier generated by the
    ToolGateway. Expired records are removed when they are read.
    """

    __tablename__ = "idempotency_keys"

    key = Column(
        String,
        primary_key=True,
    )

    result = Column(
        Text,
        nullable=False,
    )

    expires_at = Column(
        DateTime,
        nullable=False,
        index=True,
    )


class Budget(Base):
    """
    Durable budget ledger scoped to a principal.

    consumed_budget tracks cumulative usage while max_budget represents the
    configured spending ceiling.
    """

    __tablename__ = "budgets"

    principal_id = Column(
        String,
        primary_key=True,
    )

    max_budget = Column(
        Float,
        nullable=False,
    )

    consumed_budget = Column(
        Float,
        nullable=False,
        default=0.0,
    )

    currency = Column(
        String,
        nullable=False,
        default="USD",
    )